routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::resource('covenants_ibi', 'CovenantsibiController')->middleware('auth');
Route::get('covenants_ibi/destroy/{id}', 'CovenantsibiController@destroy');

Route::resource('covenants_hapoalim', 'CovenantshapoalimController')->middleware('auth');
Route::get('covenants_hapoalim/destroy/{id}', 'CovenantshapoalimController@destroy');

Route::resource('covenants_mizrahi', 'CovenantsmizrahiController')->middleware('auth');
Route::get('covenants_mizrahi/destroy/{id}', 'CovenantsmizrahiController@destroy');

Route::resource('client_data', 'ClientdataController')->middleware('auth');

// Route::post('/client_data/fetch1', 'ClientdataController@fetch1')->name('autocomplete1.fetch');

//Route::resource('customers', 'CustomerController');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/register_admin', 'RegistrationController@create');
Route::post('/home', 'RegistrationController@store');
//Route::resource('register_admin', 'RegistrationController');

Route::get('export', 'MyController@export')->name('export');
// Route::get('importExportView', 'MyController@importExportView');
Route::post('import', 'MyController@import')->name('import');
Route::post('import2', 'MyController@import2')->name('import2');
Route::post('import1', 'MyController@import1')->name('import1');
Route::get('export1', 'MyController@export1')->name('export1');
Route::get('users/code/{id}', 'UserController@code')->name('code');

Route::resource('/users', 'UserController')->middleware('auth');

Route::get('/customers', 'CustomerController@index');
Route::get('/payees', 'PayeeController@index');
Route::get('/customers/action', 'CustomerController@action')->name('customers.action');
Route::get('/payees/action', 'PayeeController@action1')->name('payees.action');

Route::resource('payees', 'PayeeController');
Route::get('payees/destroy/{id}', 'PayeeController@destroy');

Route::resource('customers', 'CustomerController');
Route::get('customers/destroy/{id}', 'CustomerController@destroy');
Route::get('/clientdatas', 'ClientdataController@create');
Route::get('customers/{id}/show', 'CustomerController@show');

Route::post('clientdatas/fetch1', 'ClientdataController@fetch1')->name('ClientdataController.fetch1');

Route::get('/all', 'ClientdataController@all');
Route::get('client_data/status1/{id}', 'ClientdataController@status1')->name('status1');
Route::get('client_data/statusclose/{id}', 'ClientdataController@statusclose')->name('statusclose');
Route::post('/customers/fetch', 'CustomerController@fetch')->name('autocomplete.fetch');
Route::post('/payees/fetch', 'PayeeController@fetch1')->name('autocomplete.fetch1');
Route::post('/client_data/fetch', 'ClientdataController@fetch')->name('autocomplete.fetchpayee');
Route::post('/client_data/fetchwithdrawer', 'ClientdataController@fetchwithdrawer')->name('autocomplete.fetchwithdrawer');


Route::post('client_data/create', 'CustomerController@store1');
Route::post('client_data/create/add', 'PayeeController@store1');

// Route::get('searchajax', ['as'=>'searchajax','uses'=>'ClientdataController@searchResponse']);

app/Payee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Payee extends Model
{
    public function users()
    {
        return $this->belongsTo('App\User');
    }
    public function clientdata()
    {
        return $this->hasMany('App\Clientdata');
    }
    protected $fillable = [
        'name', 'adrress', 'occupation','id_account','status', 'created_at', 'updated_at'
    ];
}

resources/views/payees/create.blade.php
@extends('layouts.sidebar2')
@section('content')

<h1>Create a new payee</h1>
<form method = 'post' action = "{{action('PayeeController@store')}}" >
{{csrf_field()}}      

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
  <link rel="stylesheet" href="/resources/demos/style.css">

  

<div class = "form-group">
<div class="col-md-2">
    <label class="control-label" for = "name"> Payee name </label></div>
    <div class="col-md-10">
     <input type = "text" class = "form-control" name = "name" id="name" required>
    <div id="client_nameList">
    </div>
    </div>
<br>

     <div class="col-md-2">
    <label class="control-label" for="account">Id Account</label></div>
    <div class="col-md-10">
     <input type = "number" class = "form-control" name = "account" required>
     </div>
<br>

     <div class="col-md-2">
    <label class="control-label" for="occupation">Occupation</label></div>
    <div class="col-md-10">
    <select  class="form-control" name = "occupation" required> 
  <option value="real_estate">real_estate</option>
  <option value="industry">industry</option>
  <option value="agriculture"> agriculture</option>
  
  </select>
     </div>
<br>

    <div class="col-md-2">
    <label class="control-label" for="adrress">Address</label></div>
    <div class="col-md-10">
     <input type = "text" class = "form-control" name = "adrress" required>
     </div>  
       
    <br>
    <div class="col-md-10">
    <button name="submit" type="submit" value="Save" class="btn btn-success btn-block"> Add</button></div>
    </form>
    </div>

    <script>
$(document).ready(function(){

 $('#name').keyup(function(){ 
        var query = $(this).val();
        if(query != '')
        {
         var _token = $('input[name="_token"]').val();
         $.ajax({
          url:"{{ route('autocomplete.fetch1') }}",
          method:"POST",
          data:{query:query, _token:_token},
          success:function(data){
           $('#client_nameList').fadeIn();  
                    $('#client_nameList').html(data);
          }
         });
        }
    });

    $(document).on('click', 'li', function(){  
        $('#name').val($(this).text());  
        $('#client_nameList').fadeOut();  
    });  
  

});
</script>


@endsection

resources/views/payees/edit.blade.php
@extends('layouts.sidebar3')
@section('content')

<h1>Edit a Payee</h1>
<form method='post' action="{{action('PayeeController@update', $payee ->id)}}">
  @csrf
  @method('PATCH')


  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">

  <div class="form-group">
    <div class="col-md-2">
      <label class="control-label" for="name"> Payee name </label></div>
    <div class="col-md-10">
      <input type="text" class="form-control" name="name" value="{{$payee->name}}">
    </div>
    <br>


    <div class="col-md-2">
      <label class="control-label" for="id_account">Id Account</label></div>
    <div class="col-md-10">
      <input type="number" class="form-control" name="id_account" value="{{$payee->id_account}}">
    </div>
    <br>

    <div class="col-md-2">
      <label class="control-label" for="occupation">Occupation</label></div>
    <div class="col-md-10">
      <input type="text" class="form-control" name="occupation" value="{{$payee->occupation}}">
    </div>
    <br>

    <div class="col-md-2">
      <label class="control-label" for="adrress">Address</label></div>
    <div class="col-md-10">
      <input type="text" class="form-control" name="adrress" value="{{$payee->adrress}}">
    </div>
    <br>

    <div class="col-md-2">
      <label class="control-label" for="status">Status</label></div>

    @if ($payee->status == 'Blocked')
    <div class="col-md-10" name="status" id="status">
      <input type="radio" name="status" value="{{$payee->status}}" checked="checked">
      {{$payee->status}}
      <br>
      <input type="radio" name="status" value="Authorized">Authorized
      <br>
    </div><br>
    @else
    <div class="col-md-10" name="status" id="status">
      <input type="radio" name="status" value="Authorized" checked="checked">
      {{$payee->status}}
      <br>
      <input type="radio" name="status" value="Blocked">Blocked
      <br>

    </div><br>
    @endif

  </div>

  <div class="col-md-8">
    <div class="form-group">
      <input type="submit" class="btn btn-success btn-block" name="submit" value="Save Changes">
      <!-- <input type ="submit" class = "btn btn-md btn-second" name="submit" value ="back"> -->

    </div>
  </div>
</form>




@endsection

resources/views/payees/index.blade.php
@extends('layouts.sidebar')
@section('content')

<!DOCTYPE html>
<html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<div class="w3-sidebar w3-bar-block " style="margin: 0 0 5% 0;">
  <div class="sidebar-module" style="font-family: Arial Black, Gadget, sans-serif;">
    <!-- <div class="col">
      <a href="{{ route('payees.create') }}" class="btn btn-sm btn-primary btn-create">
        @lang('Add a payee')</a>
    </div> -->
  </div>
  <div class="col">
    <a href="{{ route('payees.create') }}" class="btn btn-sm btn-primary btn-create">
      @lang('Add a payee')</a>
  </div>
</div>

<div class="container box">
  <h3 align="center">My Payees</h3><br />
  <div class="panel panel-default">
    <div class="panel-heading">Search Payee Data</div>
    <div class="panel-body">
      <div class="form-group">
        <input type="text" name="search" id="search" class="form-control" placeholder="Search" />
      </div>
      <div class="table-responsive">
        <h3 align="center">Total Data : <span id="total_records"></span></h3>
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th style="text-align:center">Payee Name</th>
              <th style="text-align:center">Address</th>
              <th style="text-align:center">Occupation</th>
              <th style="text-align:center">Id Account</th>
              <th style="text-align:center">Status</th>
              <th style="text-align:center">Edit</th>
              <th style="text-align:center">Delete</th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- Central Modal Medium -->
<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <!--Content-->
    <div class="modal-content">
      <!--Header-->
      <div class="modal-header">
        <h4 class="modal-title w-100" id="myModalLabel">Warning!</h4>
        <button type="button" class="close" data-dismiss="modal">
          &times;
        </button>
      </div>
      <!--Body-->
      <div class="modal-body">
        <div class="alert alert-danger" role="alert">
          Are you sure to delete ?
        </div>
      </div>
      <!--Footer-->
      <div class="modal-footer">
        <div class="modal-footer">
          <button type="button" name="ok_button" id="ok_button" class="btn btn-danger">OK</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>
</div>

</html>

<script>
  $(document).ready(function() {
    fetch_payee_data();

    function fetch_payee_data(query = '') {
      $.ajax({
        url: "{{ route('payees.action') }}",
        method: 'GET',
        data: {
          query: query
        },
        dataType: 'json',
        success: function(data) {
          $('tbody').html(data.table_data);
          $('#total_records').text(data.total_data);
        }
      })
    }

    $(document).on('keyup', '#search', function() {
      var query = $(this).val();
      fetch_payee_data(query);
    });

    var user_id;

    $(document).on('click', '.delete', function() {
      user_id = $(this).attr('id');
      $('#confirmModal').modal('show');
    });

    $('#ok_button').click(function() {
      $.ajax({
        url: "payees/destroy/" + user_id,
        beforeSend: function() {
          $('#ok_button').text('Deleting...');
        },
        success: function(data) {
          setTimeout(function() {
            $('#confirmModal').modal('hide');
            location.reload();
            // $('#user_table').data().ajax.reload();
            //  $("#result").load($data);
            // alert('Data Deleted');
          }, 0);
        }
      })
    });
  });
</script>

@endsection